name: ung_dung_diem_danh
description: "Ứng dụng Điểm Danh Nhân Viên với Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # API & Networking
  dio: ^5.4.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Biometric Authentication
  local_auth: ^2.1.8
  
  # Navigation
  go_router: ^13.0.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Calendar
  table_calendar: ^3.0.9
  
  # Location
  geolocator: ^11.0.0
  
  # Camera
  image_picker: ^1.0.7
  
  # Permissions
  permission_handler: ^11.2.0
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  
  # Utilities
  intl: ^0.18.1
  logger: ^2.0.2
  flutter_nfc_kit: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/
