// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UngDungDiemDanhNhanVien.Data;

#nullable disable

namespace UngDungDiemDanhNhanVien.Migrations
{
    [DbContext(typeof(UngDungDiemDanhContext))]
    [Migration("20251022102003_AddMaTheNfcToNhanVien")]
    partial class AddMaTheNfcToNhanVien
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.DiemDanh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("GioRa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GioVao")
                        .HasColumnType("datetime2");

                    b.Property<string>("KinhDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ViTriLng");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayDiemDanh");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucRa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhuongThucVao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("QuanTriVienId")
                        .HasColumnType("int")
                        .HasColumnName("NguoiTaoId");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ViDo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ViTriLat");

                    b.HasKey("Id");

                    b.HasIndex("QuanTriVienId");

                    b.HasIndex("NhanVienId", "Ngay")
                        .IsUnique();

                    b.ToTable("DiemDanh");
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.Luong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LoaiKy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("LuongGio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TongCong")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TongGioLam")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TruLuong")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("Luong");
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.NhanVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("LuongGio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaKhuonMat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSinhTracHoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaTheNfc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhauHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhongBan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaNhanVien")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.NhatKyEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LoaiEmail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienId")
                        .HasColumnType("int");

                    b.Property<string>("ThongBaoLoi")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NhanVienId");

                    b.ToTable("NhatKyEmail");
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.QuanTriVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("QuanTriVien");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@congty.com",
                            MatKhauHash = "$2a$11$c0RRqV.cYZw1NvkiPIMHM.pK9BHx4bgFNeKsugX0Oh1Cj/QBzE3FG",
                            NgayTao = new DateTime(2025, 10, 22, 17, 20, 2, 304, DateTimeKind.Local).AddTicks(5682),
                            TenDangNhap = "admin",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.DiemDanh", b =>
                {
                    b.HasOne("UngDungDiemDanhNhanVien.Models.NhanVien", "NhanVien")
                        .WithMany("DanhSachDiemDanh")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UngDungDiemDanhNhanVien.Models.QuanTriVien", "QuanTriVien")
                        .WithMany()
                        .HasForeignKey("QuanTriVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");

                    b.Navigation("QuanTriVien");
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.Luong", b =>
                {
                    b.HasOne("UngDungDiemDanhNhanVien.Models.NhanVien", "NhanVien")
                        .WithMany("DanhSachLuong")
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.NhatKyEmail", b =>
                {
                    b.HasOne("UngDungDiemDanhNhanVien.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("UngDungDiemDanhNhanVien.Models.NhanVien", b =>
                {
                    b.Navigation("DanhSachDiemDanh");

                    b.Navigation("DanhSachLuong");
                });
#pragma warning restore 612, 618
        }
    }
}
